### ISSUE TITLE
HTMD atomselect inconsistent with VMD atomselect

### ISSUE THREAD

**Issue by stefdoerr** [multiscalelab/htmd#9]
In HTMD if you do:
```python
In [4]: mol.atomselect('not protein', indexes=True)
Out[4]: array([  500,  1005,  1010, ..., 27221, 27222, 27223])
```

In VMD if you do:
```tcl
set sel [atomselect top "not protein"]
$sel get index
1010 1011 1012 1013 1014 ...
```
So two atoms from the protein (500, 1005) are recognized as "not protein" in HTMD while VMD does it correct.

I attach the file
[tempus.pdb.zip](https://github.com/multiscalelab/htmd/files/178091/tempus.pdb.zip)

Obviously kind of a major issue for building, so we should fix that asap.

**Comment by stefdoerr** [comment]
Another example of the same bug

Here the atomselection to test is: "segid P1 and not protein"
In HTMD it returns a single atom while in VMD returns no atoms.
[system.pdb.zip](https://github.com/multiscalelab/htmd/files/182237/system.pdb.zip)

**Comment by mj-harvey** [comment]
@stefdoerr, it may be unreleased, but the atom column in that second example is messed-up hydrogens are incorrectly annotated as N. What made that PDB?

**Comment by stefdoerr** [comment]
Which atoms exactly? I don't see it right now. It's an OPM PDB file and pdb2pqr adds the hydrogens.

**Comment by giadefa** [comment]
@mj-harvey you promised today

**Comment by stefdoerr** [comment]
moved it to htmdlab

**Comment by mj-harvey** [comment]
I was referring to a different one. This is conditionally not a bug,
because all the structures I have to test with are geometrically broken.
Looked as if there was a systematic problem within these OPM structures in
the posiitoning of an Oxygen in the terminal residue

On 11 May 2016 at 14:52, Stefan <notifications@github.com> wrote:

> moved it to htmdlab
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/multiscalelab/htmd/issues/9#issuecomment-218465748>
>



-- 
<https://www.acellera.com>


<https://twitter.com/acellera?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor>
    <https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/acellera>
<https://www.acellera.com/md-simulation-blog-news/>     [image:
skype:acellera] <http://is.gd/1eXkbS>

**Comment by stefdoerr** [comment]
Continue discussion here please https://github.com/multiscalelab/htmdlab/issues/74
